apiVersion: v1
kind: Service
metadata:
  name: karsajobs
  labels:
    app: karsajobs
    category: backend
spec:
  ports:
  - port: 8080
  selector:
    app: karsajobs
    category: backend
  type: NodePort
