apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
      category: message_queue
  template:
    metadata:
      labels:
        app: rabbitmq
        category: message_queue
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.11-management
          ports:
            - name: amqp
              containerPort: 5672
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /data/rabbitmq
          livenessProbe:
            exec:
              command: ['rabbitmq-diagnostics', 'status']
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 15
          readinessProbe:
            exec:
              command: ['rabbitmq-diagnostics', 'ping']
            initialDelaySeconds: 20
            periodSeconds: 60
            timeoutSeconds: 10
          imagePullPolicy: Always
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-pvc

