apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-deployment
spec:
  selector:
    matchLabels:
      app: shipping-service
      category: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: shipping-service
        category: backend
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.28
          command: ['sh', '-c', 'while ! nc -z rabbitmq.default.svc.cluster.local 5672; do sleep 1; done']
      containers:
        - name: shipping
          image: mahendrabp/shipping-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: AMQP_URL
              value: 'amqp://rabbitmq.default.svc.cluster.local:5672'
